modLoader="javafml" #mandatory
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/BarionLP/TheWitcher/issues"

[[mods]] #mandatory
    modId="the_witcher" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="The Witcher" #mandatory
    displayURL="https://www.curseforge.com/minecraft/mc-mods/the-witcher-content" #optional
    #updateJSONURL="https://change.me.example.invalid/updates.json"
    logoFile="logo.png" #optional
    credits="Thanks to Callout for his models, KaupenJoe for his amazing tutorials and every supporter" #optional
    authors="Ametrin Studios" #optional
    description='''Adds stuff from The Witcher Universe'''

[[dependencies.the_witcher]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.the_witcher]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.the_witcher]]
    modId="structure_gel"
    mandatory=true
    versionRange="[2.6.1,]"
    ordering="NONE"
    side="BOTH"