
[witcher_citadel]

	[witcher_citadel.structures]

		[witcher_citadel.structures.structure]

			[witcher_citadel.structures.structure.biomes]
				#
				# A filter for which biomes this structure should generate in. Entries are formatted as follows:
				# - Biome: "minecraft:plains"
				# - Tag: "#minecraft:is_forest"
				# - Prefix an entry with ! to exclude it: "!#minecraft:is_ocean"
				# Example: ["#minecraft:is_forest", "!minecraft:flower_forest"] This will include all biomes tagged as forests except for flower forests.
				# Default: ["#minecraft:is_taiga", "#forge:is_plains", "#forge:is_dead", "!#minecraft:is_mountain"]
				biomes = ["#minecraft:is_taiga", "#forge:is_plains", "#forge:is_dead", "!#minecraft:is_mountain"]

